### ISSUE TITLE
flutter Code93 type barCode on Android dvice,The Image is error.

### ISSUE THREAD

**Issue by GGSDDUAY** [bigship/barcode.flutter#12]
1.The string is 62959511923;
2.the image use barcod has more two black line on the right of image. 
![image](https://user-images.githubusercontent.com/10781685/65657767-669f4000-e057-11e9-9a81-421cae7106dc.png)

**Comment by GGSDDUAY** [comment]
this is the correct image.
![62959511923](https://user-images.githubusercontent.com/10781685/65657695-1c1dc380-e057-11e9-9a3d-48a4cb38acb7.png)

**Comment by GGSDDUAY** [comment]
this is the error image.
![image](https://user-images.githubusercontent.com/10781685/65657780-7880e300-e057-11e9-9f9f-eb2c8491b7e4.png)

**Comment by bigship** [comment]
@chenzhicheng163 Did you try to use a barcode scaner to actually scan the "wrong" barcode image ? Actually I can get the correct code though, the two black lines may be redundant, but it won't render the wrong code. 

Still nice to know about it, I'm going to close this issue. Feel free to reopen it when the scaner **CANNOT** recognize the correct code.

**Comment by GGSDDUAY** [comment]
Thank you for your reply！
The barcode scaner can get the correct result.
I just found that the scanner using the ios native code could not get the correct results.
