### ISSUE TITLE
some  barcode can not scan

### ISSUE THREAD

**Issue by yusonchang** [bigship/barcode.flutter#2]
test to generate two barcode, the sencod can't not scan
new BarCodeItem(type: BarCodeType.Code128, codeStr: "FS23030049234", description: "Code128", hasText: true),
new BarCodeItem(type: BarCodeType.Code128, codeStr: "FS23030049MDUxMQ==", description: "Code128", hasText: true),

![barcode](https://user-images.githubusercontent.com/10857971/49995852-50dcf480-ffc8-11e8-840b-485f0a7385bf.png)

thanks~

**Comment by mikuhl-dev** [comment]
The character M is making a huge gap. Is this intentional? I am having problem scanning barcode's with an M character.

**Comment by yusonchang** [comment]
> 角色M正在形成巨大的差距。這是故意的嗎？我在掃描帶有M字符的條形碼時遇到問題。

fix  barcode_painter.dart code128 M：0x400  change to 0x5d8

https://github.com/yusonchang/FlutterMemo/blob/master/Barcode/src/barcode_painter.dart

**Comment by yusonchang** [comment]
> The character M is making a huge gap. Is this intentional? I am having problem scanning barcode's with an M character.

> 角色M正在形成巨大的差距。這是故意的嗎？我在掃描帶有M字符的條形碼時遇到問題。

fix  barcode_painter.dart code128 M：0x400  change to 0x5d8
https://github.com/yusonchang/FlutterMemo/blob/master/Barcode/src/barcode_painter.dart

**Comment by mikuhl-dev** [comment]
@bigship There's a fix?

**Comment by bigship** [comment]
@yusonchang Seems you've solved this issue, thanks anyway. 
@MichaelPriebe yusongchang's solution is probably right. I didn't do much test, but it actually solved the 'M' character issue. I'll update the code.
