### ISSUE TITLE
Itf and codabar support

### ISSUE THREAD

**Issue by marcocondrache** [bigship/barcode.flutter#9]
Hello as title suggest we need the support to the itf and codabar format.

**Comment by v0l** [comment]
+1 for ITF support

https://www.gs1.org/sites/default/files/docs/barcodes/GS1_General_Specifications.pdf

5.3 has ITF-14 doc

**Comment by v0l** [comment]
I decided to implement this, will make a PR in a few days when done

![Screenshot_1570715067](https://user-images.githubusercontent.com/1172179/66574664-369f8300-eba7-11e9-84d3-be0d0d13b172.png)

**Comment by v0l** [comment]
Added in #19
